# Generated by Django 4.2.7 on 2026-06-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("tag", models.CharField(blank=True, max_length=255)),
                ("image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("bullets", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderId", models.CharField(max_length=100, unique=True)),
                ("items", models.JSONField()),
                ("shipping", models.JSONField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Processing", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("original_price", models.IntegerField(blank=True, null=True)),
                ("tag", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("gemstone", models.CharField(blank=True, max_length=100)),
                ("material", models.CharField(blank=True, max_length=100)),
                ("image", models.CharField(max_length=255)),
                ("meta", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("images", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
