# Generated by Django 4.2.7 on 2026-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
