# Generated by Django 4.2.7 on 2026-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_sitesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Fallback image path/URL",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Fallback image path/URL",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Upload an image file directly (will override text value if set)",
                null=True,
                upload_to="settings/",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="collections/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="value",
            field=models.TextField(
                blank=True, help_text="Text value or path/URL of the setting"
            ),
        ),
    ]
