# Generated by Django 4.2.7 on 2026-06-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_collection_image_url_product_image_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
