# Generated by Django 4.2.7 on 2026-06-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_subscriber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="gemstone",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material",
        ),
    ]
