# Generated by Django 4.2.7 on 2026-06-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_product_gemstone_remove_product_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialFeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Upload an Instagram/social feed image directly",
                        null=True,
                        upload_to="social/",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Fallback image path/URL if file is not uploaded",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        default="HAM STUDIO curated sterling silver piece",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
